"""
The report as structured data.

This is the fix for the old report generator. Previously the model emitted free
prose and the PDF layer tried to recover structure from it::

    sections = report_text.split("###")

Layout therefore depended on the model's formatting choices. Phrase a heading
differently, add a stray ``###``, or omit one, and the document broke — which
is why the output looked, in the user's words, weird.

The dependency is now inverted. The model fills a typed schema, one field at a
time, and the renderers lay out fields they already know about. Prose can never
alter the layout, and the same model drives both the HTML and the PDF, so the
two cannot drift apart.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import date


@dataclass
class Evidence:
    """A citation backing a statement in the report."""

    doc_title: str
    section: str | None
    page: int
    source_url: str
    snippet: str = ""

    @property
    def label(self) -> str:
        parts = [self.doc_title]
        if self.section:
            parts.append(self.section)
        if self.page:
            parts.append(f"p.{self.page}")
        return " - ".join(parts)


@dataclass
class KPI:
    """One headline metric on the cover strip."""

    label: str
    value: str
    caption: str = ""
    tone: str = "neutral"      # "positive" | "negative" | "neutral"


@dataclass
class Section:
    """A narrative section of the report."""

    key: str
    title: str
    summary: str = ""                              # one-line standfirst
    paragraphs: list[str] = field(default_factory=list)
    bullets: list[str] = field(default_factory=list)
    evidence: list[Evidence] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not (self.paragraphs or self.bullets)


@dataclass
class ReportModel:
    """Everything the renderers need. No renderer computes anything."""

    company_name: str
    ticker: str
    as_of: str = field(default_factory=lambda: date.today().isoformat())

    exchange: str = ""
    sector: str | None = None
    currency: str = "USD"

    # Headline verdict, all computed upstream. ``fair_value`` is the headline
    # figure the report leads with — the blended value when a triangulation was
    # built, otherwise the DCF. ``dcf_fair_value`` always holds the intrinsic
    # DCF so the two can be shown side by side.
    rating: str = "NOT RATED"
    share_price: float | None = None
    fair_value: float | None = None
    dcf_fair_value: float | None = None
    upside: float | None = None
    market_implied_growth: float | None = None
    consensus_target: float | None = None   # Wall Street consensus — the market's view

    # The investment thesis — the analytical core, rendered first. Separates
    # business quality from stock attractiveness and frames market-vs-us.
    thesis: dict | None = None

    kpis: list[KPI] = field(default_factory=list)
    sections: list[Section] = field(default_factory=list)

    # Structured blocks rendered by dedicated templates rather than as prose.
    financial_table: list[dict] = field(default_factory=list)
    forecast_table: list[dict] = field(default_factory=list)
    assumptions: list[dict] = field(default_factory=list)
    blended: dict | None = None
    scenarios: dict | None = None
    sensitivity: dict | None = None
    comps: dict | None = None
    priced_in: dict | None = None      # reverse-DCF: what the price implies per driver

    charts: dict[str, str] = field(default_factory=dict)     # name -> file path
    sources: list[dict] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    disclaimer: str = (
        "This report was generated by an automated research tool for "
        "demonstration purposes. It is not investment advice, not a "
        "recommendation to buy or sell any security, and has not been reviewed "
        "by a licensed analyst. Figures are drawn from public filings and market "
        "data sources and may contain errors. Always verify against the primary "
        "sources listed before relying on anything here."
    )

    # -- presentation helpers ---------------------------------------------

    @property
    def rating_tone(self) -> str:
        return {"BUY": "positive", "SELL": "negative"}.get(self.rating, "neutral")

    @property
    def upside_display(self) -> str:
        return f"{self.upside * 100:+.1f}%" if self.upside is not None else "-"

    def money(self, value: float | None, decimals: int = 2) -> str:
        if value is None:
            return "-"
        return f"{value:,.{decimals}f}"

    def section(self, key: str) -> Section | None:
        return next((s for s in self.sections if s.key == key), None)

    def to_dict(self) -> dict:
        return asdict(self)
